In [2]:
import torch
import numpy as np

In [4]:
t = torch.randn(2, 2, 2, 2)


tensor([[[[-0.7842,  0.0352],
          [ 1.4511, -0.5222]],

         [[ 1.1967, -0.1961],
          [ 0.3410, -0.4347]]],


        [[[ 0.4597,  1.1613],
          [ 0.8015,  1.5012]],

         [[ 0.9560, -0.4021],
          [ 0.2542,  0.3225]]]])

In [14]:
t = np.zeros((2, 2, 2, 2))
t = torch.tensor(t)
print(t)
t.dtype

tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]], dtype=torch.float64)


torch.float64

In [15]:
t1 = t.reshape(4, 4)
t1

tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]], dtype=torch.float64)


In [16]:
t2 = t.reshape(4, -1)
t2

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)

In [19]:
t3 = t.reshape(-1, 8)
t3

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=torch.float64)

In [20]:
t3[1, 1] = 1.0 # this will change t as well that t3 is pointing to via reshape (same will happen with view)
t3

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.]], dtype=torch.float64)

In [21]:
t

tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 1.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]], dtype=torch.float64)

In [30]:
t4 = torch.transpose(t3[1, :], 0, 0)
# t4 = t3[1, :]
t4

tensor([0., 1., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)

In [33]:
t1 = torch.tensor(np.random.rand(2, 3, 4))
t2 = torch.tensor(np.random.rand(5, 4, 2, 3))
t3 = torch.tensordot(t1, t2, [[0, 1], [2, 3]])
t3.shape

torch.Size([4, 5, 4])

In [35]:
t2 = t1.permute(0, 2, 1)
t2.shape

torch.Size([2, 4, 3])

In [4]:
tmp = torch.tensor(np.random.rand(6, 4))
u, s, vh = torch.linalg.svd(tmp, full_matrices = False)
print(torch.dist(tmp, u @ torch.diag(s) @ vh)) # check svd


tensor(1.4886e-15, dtype=torch.float64)


In [15]:
A = torch.randn(4, 3, 6, requires_grad=True)
B = torch.randn(3, 6, 4, requires_grad=True)
C = torch.tensordot(A, B, [[0, 1, 2], [2, 0, 1]]) 
C.backward(gradient = )
print(B.grad.shape)

torch.Size([3, 6, 4])


In [19]:
x = torch.tensor([[0, 1], [1, 0]], dtype = torch.complex64)
y = torch.tensor([[0, -1j], [1j, 0]], dtype = torch.complex64)
z = torch.tensor([[1, 0], [0, -1]], dtype = torch.complex64)
idnty = torch.eye(2, dtype = torch.complex64)

xx = torch.kron(x, x)
yy = torch.kron(y, y)

m = xx + yy

evals, evecs = torch.linalg.eigh(m)
gs = evecs[:, 0]

evals

# gs

# op = torch.kron(idnty, z)

# s = torch.tensor([0, 1, 0, 0], dtype = torch.complex64)

# torch.tensordot(op, s, [[1], [0]])


tensor([-2.,  0.,  0.,  2.])